export type RiskFlag =
  | "EARNINGS_SOON"
  | "MACRO_EVENT"
  | "WIDE_SPREADS"
  | "LOW_OI"
  | "VOLATILITY_SPIKE"
  | "RISK_IV_SPIKE"
  | "RISK_EARNINGS_WITHIN_TRADE"
  | "RISK_MACRO_EVENT"
  | "RISK_TREND_CONFLICT"
  | "RISK_CORRELATED_EXPOSURE"
  | "RISK_SECTOR_CONCENTRATION";
